---
title: "Getting started with R markdown and RStata"
author: "H. Langet, C.Festo and Samwel"
date: "`r Sys.Date()`"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R packages to install to generate dynamic reports using R and Stata

## Install RStata

Check if the package `RStata`is already installed.

```{r}
rstata_is_installed <- ("RStata" %in% installed.packages())
```

If the package `RStata`is not already installed, download and install it.

```{r}
if (!rstata_is_installed){
  install.packages("RStata")
}
```

## Install haven

Check if the package `haven`is already installed.

```{r}
if (("haven" %in% installed.packages()) == FALSE) {
  install.packages("haven")
}
```

## Install usethis

```{r}
if (("haven" %in% installed.packages()) == FALSE) {
  install.packages("usethis")
}
```

# Configure RStata

```{r}
library(RStata)
RStata::chooseStataBin()
```

You should get something 

## Open configuration file

```{r}
library(usethis)
usethis::edit_r_profile("user")
```
