project:
  type: book
  output-dir: docs

book:
  title: "Data Science for Public Health"
  subtitle: "Test"
  author:
    - name: Hélène Langet
      affiliations:
        - name: Swiss Tropical and Public Health Institute
    - name: Samwel Lwambura
      affiliations:
        - name: Ifakara Health Institute
    - name: Fenella Beynon
      affiliations:
        - name: Swiss Tropical and Public Health Institute
    - name: Silvia Cicconi
      affiliations:
        - name: Swiss Tropical and Public Health Institute
  logo: images/logo_compact.png
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - part: "------------ DAY 1 ------------"
      chapters:
        - tools_for_reproducible_data_science.qmd
        - version_control_with_git.qmd
        - rstudio_orientation.qmd
        - dynamic_documents.qmd
        - create_first_quarto_doc.qmd
        - version_control_with_git2.qmd
        - use_stata_python_with_quarto.qmd
        - import_data.qmd
    - part: "------------ DAY 2 ------------"
    - part: "------------ DAY 3 ------------"
    - references.qmd
  appendices:
    - r_setup.qmd
    - github_setup.qmd
    - import_data_from_odk_central.qmd
    - useful_resources.qmd
  page-footer: 
    left: "This book was built by [Quarto](https://quarto.org/). Copyright 2022, IHI / Swiss TPH"
    right:
      - icon: github
        href: https://github.com/Thaliehln/ds4ph/

bibliography: references.bib
csl: vancouver.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

from: markdown+emoji