project:
  type: book
  output-dir: docs

book:
  title: "Data Science for Public Health"
  subtitle: "Test"
  author:
    - name: Hélène Langet
      affiliations:
        - name: Swiss Tropical and Public Health Institute
    - name: Samwel Lwambura
      affiliations:
        - name: Ifakara Health Institute
    - name: Silvia Cicconi
      affiliations:
        - name: Swiss Tropical and Public Health Institute
  logo: images/logo_compact.png
  date: "2022-09-14"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - prerequisites.qmd
    - part: tools_for_reproducible_data_science.qmd
      chapters:
        - github.qmd
        - dynamic_documents.qmd
        - create_first_quarto_doc.qmd
        - use_stata_python_with_quarto.qmd
        - import_data.qmd
        - manipulate_data.qmd
    - part: "Day 2: Data Science for Public Health"
      chapters:
        - ds4ph_day2_session01_practical_session.qmd
    - part: "Day 3: Big data and machine learning"
      chapters: 
        - ds4ph_day3_session01_practical_session.qmd
    - useful_resources.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

from: markdown+emoji