# Prerequisites

Soon - here guidance to install the (free) software to be used in the workshop will be given.

## R installation

RStudio is an interactive desktop environment, but it is not R, nor does it include R when you download and install it. Therefore, to use RStudio, we first need to install R.

You can download R from the Comprehensive R Archive Network (CRAN)116. Search for CRAN on your browser:

Once on the CRAN page, select the version for your operating system: Linux, Mac OS X, or Windows.


## RStudio installation

This will give you several options. For what we do in this book, it is more than enough to use the free Desktop version.

After downloading, follow the installation wizard on your computer.

## Install Quarto

To install Quarto: https://quarto.org/docs/get-started/. After downloading, follow the installation wizard on your computer. When it is complete, you will not see an application or any new software, but it is now available to RStudio (as well as all other applications on your computer, including the command line).

## GitHub account

## GitHub desktop

To install GitHub Desktop: link. After downloading, follow the installation wizard on your computer.

### How to connect your GitHub account to GitHub Desktop?

#### Authenticating to GitHub

To connect to GitHub Desktop with GitHub, you will need to authenticate your GitHub account. 

1. Use the File menu, then click Options.
2. In the Options window, select Accounts. 
3. To the right of "GitHub.com," click Sign in.
4. In the "Sign in Using Your Browser" pane, click Continue With Browser. GitHub Desktop will open your default browser.
5. To authenticate to GitHub, type your GitHub.com credentials and click Sign in. Alternatively, if you were already signed in to GitHub, follow the prompts to return to GitHub Desktop to finish authenticating.
6. After GitHub authenticates your account, follow the prompts to return to GitHub Desktop.


